name: Backend Deployment

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    name: "Deploy to Render"
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install uv
        run: pip install uv

      - name: Install dependencies and run tests
        run: |
          cd backend
          uv venv
          uv pip install -r requirements.lock
          uv run python manage.py test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deployment
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}