name: Frontend Deployment

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    name: "Deploy to Netlify"
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.19.0
          cache: 'pnpm'
          
      # Setup pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 10.15.0

      - name: Install and build frontend
        run: |
          cd frontend
          pnpm install
          pnpm build

      - name: Deploy to Netlify
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}